wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689441763.564398
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.11.3
      5: 0.15.5
      6: 4.25.1
      8:
      - 3
      - 5
